---
- name: setup debian repositories
  apt_repository: repo={{item}} state=present
  with_items: debian_repositories
  notify:
    - update apt_cache

- name: install common tools
  apt: pkg={{item}} state=present
  with_items:
    - htop
    - vim-nox
    - iotop
    - curl
    - git
    - tcpdump
    - sshpass

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{item}}" state=present
  when: hostvars[item].ansible_host is defined
  with_items: groups['all']
  
- name: Copy ansible inventory file to default location
  copy: src=hosts/hosts dest=/etc/ansible/hosts mode=0644

- name: create ansible logs folder
  file: path=/var/log/ansible/junos state=directory mode=0777 owner=vagrant