---
- name: install python tools
  apt: pkg={{item}} state=present
  with_items:
   - python-dev
   - python-pip
   - libxml2-dev
   - libxslt-dev
   - libssl-dev
   - libffi-dev
   - python-lxml
   - python-ipdb
   - python-xmltodict
   - ipython
   - ipython-notebook
   - virtualenvwrapper

- name: upgrade python setuptools from backports
  apt: name=python-setuptools state=latest default_release=jessie-backports

- name: install python cryptography module
  pip: name=cryptography version=1.2.1

- name: install Juniper-eznc client
  pip: name=junos-eznc version=1.3.1

- name: check if Juniper.junos role installed
  shell: ansible-galaxy list | grep Juniper.junos || echo False
  changed_when: "'False' in junos_role_status.stdout"
  register: junos_role_status

- name: Install Juniper.junos role if missing
  shell: ansible-galaxy install Juniper.junos
  when: "'Juniper.junos' not in junos_role_status.stdout"
