---
- name: install python tools
  apt: pkg={{item}} state=present
  with_items:
   - python-dev
   - python-pip
   - libxml2-dev
   - libxslt-dev
   - libssl-dev
   - libffi-dev
   - python-lxml
   - python-ipdb
   - python-xmltodict
   - ipython
   - ipython-notebook
   - virtualenvwrapper


- name: install Juniper-eznc client
  pip: name=junos-eznc virtualenv=/home/vagrant/venv

- name: check if Juniper.junos role installed
  shell: ansible-galaxy list | grep Juniper.junos || echo False
  changed_when: "'False' in junos_role_status.stdout"
  register: junos_role_status

- name: Install Juniper.junos role if missing
  shell: ansible-galaxy install Juniper.junos
  when: "'Juniper.junos' not in junos_role_status.stdout"
