---
- name: Checking NETCONF connectivity
  wait_for: host={{ inventory_hostname }} port=830 timeout=5

- name: get facts from junos
  junos_get_facts: host={{ inventory_hostname }}
  register: junos

- name: version
  debug: msg="{{ junos.facts.version }}"